### ISSUE TITLE
Remove references to Balsamiq as high fidelity

### ISSUE THREAD

**Issue by berziiii** [ga-wdi-boston/project-planning-wireframes#6]
Balsamiq is intended for low to mid fidelity mock ups, not high (IMHO, axure or invision) would be high fidelity.

**Comment by jrhorn424** [comment]
Agreed.

**Comment by BenGitsCode** [comment]
Can this be closed between f548f00 and 3f4e8ef ? @jrhorn424 I will defer to you despite Brian opening the issue.

**Comment by BenGitsCode** [comment]
Can this be considered closed between 3f4e8ef  and f548f00 ?

**Comment by jrhorn424** [comment]
Sure, thanks. See #9.
